# Generated by Django 5.0.6 on 2025-05-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('customerName', models.CharField(max_length=50)),
                ('contactLastName', models.CharField(max_length=50)),
                ('contactFirstName', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('addressLine1', models.CharField(max_length=50)),
                ('addressLine2', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('postalCode', models.CharField(blank=True, max_length=15, null=True)),
                ('country', models.CharField(max_length=50)),
                ('creditLimit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employeeNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('lastName', models.CharField(max_length=50)),
                ('firstName', models.CharField(max_length=50)),
                ('extension', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('jobTitle', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('officeCode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('addressLine1', models.CharField(max_length=50)),
                ('addressLine2', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(max_length=50)),
                ('postalCode', models.CharField(max_length=15)),
                ('territory', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'offices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('orderDate', models.DateField()),
                ('requiredDate', models.DateField()),
                ('shippedDate', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=15)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantityOrdered', models.IntegerField()),
                ('priceEach', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orderLineNumber', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'orderdetails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkNumber', models.CharField(max_length=50)),
                ('paymentDate', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'payments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productCode', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=70)),
                ('productScale', models.CharField(max_length=10)),
                ('productVendor', models.CharField(max_length=50)),
                ('productDescription', models.TextField()),
                ('quantityInStock', models.SmallIntegerField()),
                ('buyPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MSRP', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductLine',
            fields=[
                ('productLine', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('textDescription', models.TextField(blank=True, null=True)),
                ('htmlDescription', models.TextField(blank=True, null=True)),
                ('image', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'productlines',
                'managed': False,
            },
        ),
    ]
